version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sgi_postgres
    environment:
      POSTGRES_USER: sgi_user
      POSTGRES_PASSWORD: sgi_pass
      POSTGRES_DB: sgi_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U sgi_user -d sgi_db']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sgi_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
